name: Studio 49 Production
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28850229014642537
title: Studio 49 Production
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1b1a7'
    - '#f2efdf'
    - '#e4e2d3'
    - '#c6c5b9'
    - '#da8326'
  brandStrength: 1
  lightness: 0.8650807698722929
  saturation: 0.875
  rhythmicContrast: 0.5620675077661872
purpose: []
