title: Studio 49 Production
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7365592
  brandStrength: 0.688172
  lightness: 0.8650808
  brandColors:
    - '#b1b1a7'
    - '#f2efdf'
    - '#e4e2d3'
    - '#c6c5b9'
    - '#da8326'
  rhythmicContrast: 0.5620675
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Studio 49 Production
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.749104
layout_spectrum: 0.8225806
