name: Studio 49 Production
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28850229014642537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6757643686141819
  lightness: 0.8650807698722929
  saturation: 0.33541781175881624
  rhythmicContrast: 0.5620675077661872
purpose: []
